package ruleta;

public enum resultadoNumero {

	CERO, UNO, DOS, TRES, CUATRO, CINCO, SEIS, SIETE, OCHO, NUEVE, DIEZ,
	ONCE, DOCE, TRECE, CATORCE, QUINCE, DIECISEIS, DIECISIETE, DIECIOCHO, DIECINUEVE, 
	VEINTE, VEINTIUNO, VEINTIDoS, VEINTITReS, VEINTICUATRO, VEINTICINCO, VEINTISeIS, VEINTISIETE, VEINTIOCHO, VEINTINUEVE, 
	TREINTA, TREINTAYUNO, TREINTAYDOS, TREINTAYTRES, TREINTAYCUATRO, TREINTAYCINCO, TREINTAYSEIS;

}
